# Generated by Django 5.1.3 on 2024-11-10 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cantante', models.BooleanField(default=False)),
                ('instrumento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('creacion_registro', models.DateField(auto_now_add=True)),
                ('agregado_por', models.DateField()),
                ('artista_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registro_de_artistas.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('artistas', models.ManyToManyField(related_name='grupos', through='registro_de_artistas.ArtistaGrupo', to='registro_de_artistas.artista')),
            ],
        ),
        migrations.AddField(
            model_name='artistagrupo',
            name='grupo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_de_artistas.grupo'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('grupo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumes', to='registro_de_artistas.grupo')),
            ],
        ),
    ]
